### ISSUE TITLE
Make file for Windows systems

### ISSUE THREAD

**Issue by MalteKurz** [MalteKurz/VineCopulaMatlab#8]
Issue reported by Ben van der Meij at [Matlab's File Exchange](http://www.mathworks.com/matlabcentral/fileexchange/46412-vine-copulas-with-matlab):

"Do you also have a version for windows systems?"

**Comment by MalteKurz** [comment]
The makefiles of VineCopulaMatlab and the submodule VineCopulaCPP have been revised. Windows is now also partly supported (MinGW-w64 C++ compiler only).

In the documentations (cf. http://maltekurz.github.io/VineCopulaMatlab/installVineCPP/) it is described how one can use the MinGW-w64 C++ compiler to install the VineCopulaMatlab toolbox under Windows. I tested it with Matlab 2014b and Windows 7.

**Comment by yaooo99** [comment]
Hi Malte,

I followed the instruction to install Vine Copula but I failed at last step.  I got the following messages, 

if nothing in the folder src
 
$ make install prefix=/c/users/yao/documents/dir bootsincludedir=/c/users/yao/documents/boots
make install -C src
make[1]: Entering directory `/c/users/yao/documents/vinecopula/src'
make[1]: *** No rule to make target `install'.  Stop.
make[1]: Leaving directory `/c/users/yao/documents/vinecopula/src'
make: *** [InstallLibrary] Error 2

if I copied all files of VineCopulaCPP to the folder src

$ make install prefix=/c/users/yao/documents/copula bootsincludedir=/c/users/yao/documents/boots
make install -C src
make[1]: Entering directory `/c/users/yao/documents/vinecopula/src'
cp libVineCopulaCPP.dll /c/users/yao/documents/copula/lib/
cp: target `/c/users/yao/documents/copula/lib/' is not a directory: No such file or directory
make[1]: *** [WindowsInstall] Error 1
make[1]: Leaving directory `/c/users/yao/documents/vinecopula/src'
make: *** [InstallLibrary] Error 2

Could you tell me what step I did wrong?

**Comment by yaooo99** [comment]
Hi Malte,

Now, I got the following messages

$ make install prefix=/c/users/yao/documents/copula boostincludedir=/users/yao/
documents/boots
make install -C src
make[1]: Entering directory `/c/users/yao/documents/vinecopulamatlab-master/src'

cp libVineCopulaCPP.dll /c/users/yao/documents/copula/lib/
cp: cannot stat `libVineCopulaCPP.dll': No such file or directory
make[1]: *** [WindowsInstall] Error 1
make[1]: Leaving directory `/c/users/yao/documents/vinecopulamatlab-master/src'
make: *** [InstallLibrary] Error 2

What is the problem? I am looking forward your responses. 

Thanks

**Comment by MalteKurz** [comment]
- To me that looks like the cloning of the submodule VineCopulaCPP wasn't successful or maybe the compilation failed.
- Have you tried to clone manually the submodule https://github.com/MalteKurz/VineCopulaCPP and to compile it?
